#!/bin/bash
export GH_TOKEN=$(cat /etc/github/token)

# Single behave run producing both the human-readable log and the machine-readable
# results, so the two can never disagree with each other (running behave twice, once
# per format, let the reported counts and the displayed log come from two separate
# test executions racing the same not-yet-ready service).
behave -f plain --summary -o summary.txt -f json -o results.json

# Scenario-level counts via jq, not grep -c: results.json is one compact line, so
# grep -c counts matching *lines* (0 or 1), not occurrences of the pattern within it —
# and a naive substring count would also double-count step-level "status" fields
# nested inside each scenario.
TOTAL=$(jq -r '[.[].elements[]? | select(.type=="scenario")] | length' results.json 2>/dev/null || echo 0)
PASSED=$(jq -r '[.[].elements[]? | select(.type=="scenario" and .status=="passed")] | length' results.json 2>/dev/null || echo 0)
FAILED=$(jq -r '[.[].elements[]? | select(.type=="scenario" and .status=="failed")] | length' results.json 2>/dev/null || echo 0)
ERRORS=$(jq -r '[.[].elements[]? | select(.type=="scenario" and .status=="error")] | length' results.json 2>/dev/null || echo 0)

REPORT_BODY=$(cat <<EOF
## 🧪 Behave Test Results
| Status | Count |
| :--- | :--- |
| ✅ Passed | $PASSED |
| ❌ Failed | $FAILED |
| 📋 Total | $TOTAL |
| ⚠️ Errors | $ERRORS |

<details>
<summary><b>Click to see full test logs</b></summary>

\`\`\`text
$(cat summary.txt)
\`\`\`
</details>

*Generated by Kubernetes Job: ${HOSTNAME}*
EOF
)

PAYLOAD=$(jq -n --arg body "$REPORT_BODY" '{body: $body}')

curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${REPO_SLUG}/issues/${PR_NUMBER}/comments" \
  -d "$PAYLOAD"

STATE="success"
if [ "$FAILED" -ne "0" ] || [ "$ERRORS" -ne "0" ]; then
  STATE="failure"
fi

curl -X POST \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/${REPO_SLUG}/statuses/${COMMIT_SHA}" \
  -d "{
    \"state\": \"$STATE\",
    \"target_url\": \"https://your-logs-link.com\",
    \"description\": \"Behave Tests: $PASSED passed, $FAILED failed, $ERRORS errors\",
    \"context\": \"kubernetes/behave-tests\"
  }"
