#!/bin/bash
export GH_TOKEN=$(cat /etc/github/token)

behave -f plain --summary > summary.txt 2>&1
behave -f json -o results.json > /dev/null 2>&1 || true

TOTAL=$(grep -c '"type": "scenario"' results.json | tr -d '\n' || echo "0")
FAILED=$(grep -c '"status": "failed"' results.json | tr -d '\n' || echo "0")
PASSED=$(grep -c '"status": "passed"' results.json | tr -d '\n' || echo "0")
ERRORS=$(grep -c '"status": "error"' results.json | tr -d '\n' || echo "0")


REPORT_BODY=$(cat <<EOF
## 🧪 Behave Test Results
| Status | Count |
| :--- | :--- |
| ✅ Passed | $PASSED |
| ❌ Failed | $FAILED |
| 📋 Total | $TOTAL |
| ⚠️ Errors | $ERRORS |

<details>
<summary><b>Click to see full test logs</b></summary>

\`\`\`text
$(cat summary.txt)
\`\`\`
</details>

*Generated by Kubernetes Job: ${HOSTNAME}*
EOF
)

PAYLOAD=$(jq -n --arg body "$REPORT_BODY" '{body: $body}')

curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/lukasb27/fermentation-station-agent/issues/$PR_NUMBER/comments \
  -d "$PAYLOAD"

STATE="success"
if [ "$FAILED" -ne "0" ] || [ "$ERRORS" -ne "0" ]; then
  STATE="failure"
fi

curl -X POST \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/repos/lukasb27/fermentation-station-agent/statuses/051db5850a5e924549a7c006cd6913b5622b1754 \
  -d "{
    \"state\": \"$STATE\",
    \"target_url\": \"https://your-logs-link.com\",
    \"description\": \"Behave Tests: $PASSED passed, $FAILED failed, $ERRORS errors\",
    \"context\": \"kubernetes/behave-tests\"
  }"