apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ APP_NAME }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/fermentation-station-agent.git
    targetRevision: {{ BRANCH }}
    path: k8s
    kustomize:
      images:
        - lukasball/fermentation-station-agent={{ IMAGE }}
      commonAnnotations:
        prNumber: "{{PR_NUMBER }}"
        sha: {{ SHA }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ NAMESPACE }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true