apiVersion: v1
kind: Service
metadata:
  labels:
    app: fermentation-station-agent
  name: fermentation-station-agent-service
  namespace: lukas-test-environment
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fermentation-station-agent
status:
  loadBalancer: {}